export default {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  safelist: [
    "bg-mainyellow",
    "bg-mainorange",
    "bg-mainpink",
    "bg-mainblue",
    "bg-maingreen",
    "bg-mainred",
    "bg-mainpurple",
    "outline-mainyellow",
    "outline-mainorange",
    "outline-mainpink",
    "outline-mainblue",
    "outline-maingreen",
    "outline-mainred",
    "outline-mainpurple",
    "border-mainyellow",
    "border-mainorange",
    "border-mainpink",
    "border-mainblue",
    "border-maingreen",
    "border-mainred",
    "border-mainpurple",
    "text-maingreen",
    "text-mainyellow",
    "text-mainred",
  ],
};
